version: "3"

services:

  runtime-setup:
    image: redistack:22.04-5.9
    build:
      args:
        ubuntu_version: "jammy"
        swift_version: "5.9"

  documentation-check:
    image: redistack:22.04-5.9

  test:
    image: redistack:22.04-5.9
    environment:
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error

  shell:
    image: redistack:22.04-5.9
