version: "3"

services:

  runtime-setup:
    image: redistack:22.04-5.9
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.9-jammy"

  documentation-check:
    image: redistack:22.04-5.9

  test:
    image: redistack:22.04-5.9
    environment:
      - IMPORT_CHECK_ARG=--explicit-target-dependency-import-check error
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: redistack:22.04-5.9
