name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "RediStack"

  unit-tests:
    name: Unit tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      linux_exclude_swift_versions: "[{\"swift_version\": \"5.8\"}]"
      # since we don't have systemctl, we run the redis server manually in the background
      linux_pre_build_command: apt-get update -y && apt-get install redis -y
      linux_build_command: bash -c 'nohup redis-server & swift test'
      enable_windows_checks: false
